import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { volkswagen } from "./fonts";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MOM'S Natural Foods",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" className={`${volkswagen.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

         <link
          rel="preload"
          href="/bg2.jpg" // Change this to the path of your first background image
          as="image"
        />
        {children}
      </body>
    </html>
  );
}
